function Hd = ButterWorthIIR(Fc)
%Fc should be a list of size 2
%TASK4IIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and Signal Processing Toolbox 8.0.
% Generated on: 12-Jul-2019 16:27:16

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

N   = 50;   % Order

% Construct an FDESIGN object and call its BUTTER method.
% Fc(1) defines low cut off Fc(2) defines high cut off
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc{1}, Fc{2}, Fs);
Hd = design(h, 'butter');

% [EOF]

end