function Hd = gEquiFIR
%GEQUI Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 14-Jul-2019 15:25:47

% Generalized REMEZ FIR Bandpass filter designed using the FIRGR function.

% All frequency values are in Hz.
Fs = 16000;  % Sampling Frequency

Fstop1 = 200;             % First Stopband Frequency
Fpass1 = 250;             % First Passband Frequency
Fpass2 = 500;             % Second Passband Frequency
Fstop2 = 550;             % Second Stopband Frequency
Dstop1 = 0.0001;          % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 200;             % Density Factor

% Calculate the coefficients using the FIRGR function.
b  = firgr('mineven', [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 ...
           0 1 1 0 0], [Dstop1 Dpass Dstop2], {dens});
Hd = dfilt.dffir(b);

% [EOF]

end